### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vladbndko** [andersanmiguel/cockpit-github-webhook#2]
Hello, @andersanmiguel!
Thanks for your package, it's cool! But it includes a broken link, I've fixed it and made [PR](https://github.com/andersanmiguel/cockpit-github-webhook/pull/1). Could you, please, accept it?
**Thanks one more time, it saved me a lot of time.**

**Comment by andersanmiguel** [comment]
Yes, sorry for the delay, it's already accepted, thank you for the pr.
